# Generated by Django 3.2 on 2021-04-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_published_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='published_on',
        ),
    ]
